name: Generate Changelog

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
      head_branch:
        required: true
        type: string

jobs:
  generate-prompt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch base branch
        run: |
          git fetch origin ${{ inputs.base_branch }} --depth=1  # Asegura que tenemos la rama base

      - name: Get PR Changes
        id: changed_files
        run: |
          FILES=$(git diff --name-only origin/${{ inputs.base_branch }} ${{ inputs.head_branch }} | tr '\n' ', ')
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Generate Prompt
        id: generate_prompt
        run: |
          echo "PROMPT=Analyze the following changes and generate a structured changelog: $FILES" >> $GITHUB_ENV

      - name: Output Prompt
        run: |
          echo "Generated Prompt: ${{ env.PROMPT }}"
