name: Generate Changelog

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
      head_branch:
        required: true
        type: string

jobs:
  generate-prompt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Trae todo el historial y ramas
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch base branch
        run: |
          git fetch origin ${{ inputs.base_branch }} --depth=1
          git checkout ${{ inputs.head_branch }}  # Asegura que estamos en la rama correcta

      - name: Get PR Changes (Files & Content)
        id: changed_files
        run: |
          FILES=$(git diff --name-only origin/${{ inputs.base_branch }} ${{ inputs.head_branch }} | tr '\n' ', ')
          DIFF=$(git diff --unified=0 origin/${{ inputs.base_branch }} ${{ inputs.head_branch }} | tail -c 30000)  # Limita tamaño

          # Limpiar el contenido de 'DIFF' eliminando caracteres no válidos
          CLEAN_DIFF=$(echo "$DIFF" | sed 's/[^[:print:]\t]//g' | tr -s '\n' ' ')

          # Guardar la salida en el entorno de GitHub
          echo "FILES=$FILES" >> $GITHUB_ENV
          echo "DIFF=$CLEAN_DIFF" >> $GITHUB_ENV

      - name: Generate Prompt
        id: generate_prompt
        run: |
          echo "PROMPT=Analyze the following changes and generate a structured changelog:\nFiles: $FILES\nDiff:\n$CLEAN_DIFF" >> $GITHUB_ENV

      - name: Output Prompt
        run: |
          echo "Generated Prompt: ${{ env.PROMPT }}"
